#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
# Accepts 4 parameters
# The path to the file to be transferred
# 2. The IP of the server we want to transfer the file to
# 3. The username scp connects with
# 4. The path to the SSH private key that scp uses

if [[ $# -lt 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
path_to_file = $1
ip = $2
username = $3
ssh_key = $4

export SCP_OPTIONS="-o StrictHostKeyChecking=no"
scp -i "$ssh_key" "$path_to_file" "$username"@"$ip":~/
