#!/usr/bin/env bash

# using scp command to transfer from local machine to a remote server verified the number o argument on the command line

# disable strict key check

# Transfers a file from our client to a server:
# Accepts 4 parameters:
## 1:The path to the file to be transferred
## 2:The IP of the server we want to transfer the file to
## 3:The username scp connects with
## 4:The path to the SSH private key that scp uses

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
