#!/bin/bash

# using scp command to transfer from local machine to a remote server verified the number o argument on the command line

# disable strict key check
export SCP_OPTIONS="-o StrictHostKeyChecking=no"
file_path="$1"
server_ip="$2"
username="$3"
ssh_path="$4"

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]
then
	scp SCP_OPTIONS "$file_path" "$username@$server_ip":~/
else
	scp -i "$ssh_path" SCP_OPTIONS "$file_path" "$username@$server_ip":~/
fi
