#!/usr/bin/env bash
# configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \\trewrite ^/redirect https://www.geeksforgeeks.org/sed-command-in-linux-unix-with-examples permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
