#!/usr/bin/env bash
#  Configuring severs (Nginx) to make HTTP response contains a custom header (on web-01 and web-02)
# HTTP header must be X-Served-By: server_name


sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

# index page for /root
echo "Hello World!" | sudo tee /var/www/html/index.html

# configuresever to response to header and rediretion
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;\n\trewrite ^\/redirect_me https://github.com/Beloveyeboah permanent;' /etc/nginx/sites-enabled/default

# create a custom pag error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# test the nginx engine
sudo nginx -t

# restart the server
sudo service nginx restart
