#!/usr/bin/env bash
# script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  beloveyeboah-frontend
        bind *:80
        mode http
        default_backend beloveyeboah-backend
backend beloveyeboah-backend
        balance roundrobin
        server 255269-web-01 34.239.207.252:80 check
        server 255269-web-02 54.237.76.244:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

# check if succesfull
sudo haproxy -c -V -f /etc/haproxy/haproxy.cfg
