#!/usr/bin/python3
""" sending a query to Reddit API"""

import json
import requests


def number_of_subscribers(subreddit):
    """ make a request Reddit Api """

    if subreddit is None or not isinstance(subreddit, str):
        return 0
    user = {"User-Agent": "beloveyeboah"}
    url = 'https://www.reddit.com/r/{}/about.json'.format(subreddit)
    req = requests.get(url, headers=user)
    if req.status_code == 200:
        data = req.json()
        sub_count = data['data']['subscribers']
        return sub_count
    else:
        return 0
