#!/usr/bin/python3
"""function that queries the Reddit API and prints the titles
of the first 10 hot posts listed for a given subreddit.
"""

import json
import requests


def top_ten(subreddit):
    """ prints the titles of the first 10 hot posts"""

    if subreddit is None or type(subreddit) != "str":
        print("None")
    user = {"User-Agent": "beloveyeboah"}
    params = {'limit': 10}
    url = 'https://www.reddit.com/r/{}/about.json'.format(subreddit)
    req = requests.get(url, headers=user, params=params)
    response = req.json()
    try:
        info = results.get('data').get('children')

        for i in info:
            print(i.get('data').get('title'))
    except Exception:
        print("None")
