#!/usr/bin/env bash
# the scripts Creates the file /var/run/myscript.pid containing its PID
# shellcheck disable=SC2064

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
